# File: hc/accounts/tests/test_createproject.py  <-- New file or add to existing tests
from __future__ import annotations

from unittest.mock import Mock, patch

from django.contrib.auth.models import User
from django.core.management import call_command # Can be useful, but let's stick to direct handle call with patching

from hc.accounts.management.commands.createproject import Command
from hc.accounts.models import Project
from hc.test import BaseTestCase


class CreateProjectTestCase(BaseTestCase):
    # Test successful creation with interactive prompts
    def test_it_creates_project_interactively(self) -> None:
        cmd = Command(stdout=Mock())
        # Note: createproject does not use getpass
        with patch(cmd.__module__ + ".input") as mock_input:
            # Simulate user input: first email, then project name
            mock_input.side_effect = ["alice@example.org", "Alice's Test Project"]
            # Call handle with default options (all keys false)
            cmd.handle(
                enable_api_key=False,
                enable_api_key_readonly=False,
                enable_ping_key=False
            )

        # Verify project exists and has correct owner and name
        p = Project.objects.get(owner=self.alice, name="Alice's Test Project")
        self.assertEqual(p.owner, self.alice)
        # Check that keys were *not* generated by default
        self.assertFalse(p.api_key)
        self.assertFalse(p.api_key_readonly)
        self.assertIsNone(p.ping_key)
        # Check that badge_key *was* generated
        self.assertTrue(p.badge_key)

    # Test handling of non-existent user email initially
    def test_it_handles_non_existent_user(self) -> None:
        cmd = Command(stdout=Mock(), stderr=Mock())
        with patch(cmd.__module__ + ".input") as mock_input:
            # Simulate: 1. bad email, 2. good email, 3. project name
            mock_input.side_effect = [
                "noone@example.org",
                "alice@example.org",
                "Retry Project",
            ]
            cmd.handle(
                enable_api_key=False,
                enable_api_key_readonly=False,
                enable_ping_key=False
            )

        # Check stderr was called for the error message
        self.assertTrue(cmd.stderr.write.called)
        # Verify project was eventually created for the correct user
        p = Project.objects.get(owner=self.alice, name="Retry Project")
        self.assertEqual(p.owner, self.alice)

    # Test creating with writeable API key enabled via options
    def test_it_creates_with_api_key(self) -> None:
        cmd = Command(stdout=Mock())
        with patch(cmd.__module__ + ".input") as mock_input:
            mock_input.side_effect = ["alice@example.org", "API Key Project"]
            # Pass options directly to handle
            cmd.handle(
                enable_api_key=True, # Enable this key
                enable_api_key_readonly=False,
                enable_ping_key=False
            )

        p = Project.objects.get(owner=self.alice, name="API Key Project")
        self.assertTrue(p.api_key) # Should be generated
        self.assertEqual(len(p.api_key), 32) # Check length based on _generate_key
        self.assertFalse(p.api_key_readonly)
        self.assertIsNone(p.ping_key)

    # Test creating with read-only API key enabled via options
    def test_it_creates_with_readonly_api_key(self) -> None:
        cmd = Command(stdout=Mock())
        with patch(cmd.__module__ + ".input") as mock_input:
            mock_input.side_effect = ["alice@example.org", "RO Key Project"]
            cmd.handle(
                enable_api_key=False,
                enable_api_key_readonly=True, # Enable this key
                enable_ping_key=False
            )

        p = Project.objects.get(owner=self.alice, name="RO Key Project")
        self.assertFalse(p.api_key)
        self.assertTrue(p.api_key_readonly) # Should be generated
        self.assertEqual(len(p.api_key_readonly), 32)
        self.assertIsNone(p.ping_key)

    # Test creating with ping key enabled via options
    def test_it_creates_with_ping_key(self) -> None:
        cmd = Command(stdout=Mock())
        with patch(cmd.__module__ + ".input") as mock_input:
            mock_input.side_effect = ["alice@example.org", "Ping Key Project"]
            cmd.handle(
                enable_api_key=False,
                enable_api_key_readonly=False,
                enable_ping_key=True # Enable this key
            )

        p = Project.objects.get(owner=self.alice, name="Ping Key Project")
        self.assertFalse(p.api_key)
        self.assertFalse(p.api_key_readonly)
        self.assertTrue(p.ping_key) # Should be generated
        self.assertEqual(len(p.ping_key), 22) # Check length based on _generate_key

    # Test creating with multiple keys enabled
    def test_it_creates_with_multiple_keys(self) -> None:
        cmd = Command(stdout=Mock())
        with patch(cmd.__module__ + ".input") as mock_input:
            mock_input.side_effect = ["alice@example.org", "Multi Key Project"]
            cmd.handle(
                enable_api_key=True, # Enable
                enable_api_key_readonly=False, # Disable
                enable_ping_key=True # Enable
            )

        p = Project.objects.get(owner=self.alice, name="Multi Key Project")
        self.assertTrue(p.api_key)
        self.assertFalse(p.api_key_readonly)
        self.assertTrue(p.ping_key)
